// Code generated by "stringer -type=TreeType"; DO NOT EDIT.

package tree

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TreeTypeUnknown-0]
	_ = x[TreeTypeTableInterior-1]
	_ = x[TreeTypeTableLeaf-2]
	_ = x[TreeTypeIndexInterior-3]
	_ = x[TreeTypeIndexLeaf-4]
}

const _TreeType_name = "TreeTypeUnknownTreeTypeTableInteriorTreeTypeTableLeafTreeTypeIndexInteriorTreeTypeIndexLeaf"

var _TreeType_index = [...]uint8{0, 15, 36, 53, 74, 91}

func (i TreeType) String() string {
	if i < 0 || i >= TreeType(len(_TreeType_index)-1) {
		return "TreeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TreeType_name[_TreeType_index[i]:_TreeType_index[i+1]]
}
