// Code generated by "stringer -type=RegisterType"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegisterTypeUnknown-0]
	_ = x[RegisterTypeNull-1]
	_ = x[RegisterTypeInt-2]
	_ = x[RegisterTypeFloat-3]
	_ = x[RegisterTypeString-4]
	_ = x[RegisterTypeBlob-5]
}

const _RegisterType_name = "RegisterTypeUnknownRegisterTypeNullRegisterTypeIntRegisterTypeFloatRegisterTypeStringRegisterTypeBlob"

var _RegisterType_index = [...]uint8{0, 19, 35, 50, 67, 85, 101}

func (i RegisterType) String() string {
	if i < 0 || i >= RegisterType(len(_RegisterType_index)-1) {
		return "RegisterType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegisterType_name[_RegisterType_index[i]:_RegisterType_index[i+1]]
}
