name: Test
on: [push, pull_request]

# https://github.com/mvdan/github-actions-golang
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: SQLite Version
      run: |
        which sqlite3
        sqlite3 --version
    - name: Test
      run: go test -v -race ./...
    - name: Test (Flakiness)
      run: go test -v -race -count=5 ./...
